server:
  port: 8010

# 应用名称(nacos会将改名称当作服务名称)
spring:
  application:
    name: order-service
  cloud:
    nacos:
      namespace: 96ac4ca0-9c69-49a3-b4b2-5e0367e47e4b
      server-addr: 39.99.136.166:8848
      username: visitor
      password: 123456

# springboot 默认的日志级别是info,feign的debug日志就不会输入
logging:
  level:
    com.liqiuyue.order.feign: debug

# 局部配置
feign:
  client:
    config:
      stock-service:
        loggerLevel: FULL
#        contract: feign.Contract.Default
        connectTimeout: 5000
        readTimeout: 3000
        requestInterceptors[0]: com.liqiuyue.order.interceptor.feign.CustomerFeignInterceptor