server:
  port: 8015

# 应用名称(nacos会将改名称当作服务名称)
spring:
  application:
    name: stock-service
  cloud:
    nacos:
      server-addr: 39.99.136.166:8848
      namespace: 96ac4ca0-9c69-49a3-b4b2-5e0367e47e4b
      username: nacos
      password: nacos
